import {
  Component, OnInit, OnDestroy,
  ChangeDetectorRef, inject, afterNextRender
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { AuthService } from '../services/auth.service';
import {
  CartService, CartState, CartItemDTO, VendorCartBucket,
  WalletResponse, CartResponseDTO,
} from '../services/cart.service';
import { ToastService } from '../services/toast.service';

@Component({
  selector: 'app-cart-view',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './cart-view.component.html',
  styleUrls: ['./cart-view.component.css']
})
export class CartViewComponent implements OnInit, OnDestroy {
  private authSvc = inject(AuthService);
  private cartSvc = inject(CartService);
  private router  = inject(Router);
  private toast   = inject(ToastService);
  private cdr     = inject(ChangeDetectorRef);

  userId!: number;
  cartState!: CartState;
  isLoading = true;
  hasError  = false;

  /* Order placement state */
  isProcessing = false;
  orderSuccess = false;
  orderError   = '';
  /** All tokens generated by the multi-vendor split */
  confirmedOrders: { token: string; vendor: string; amount: number }[] = [];
  confirmedTotal = 0;
  walletBalance  = 0;

  private sub?: Subscription;

  get buckets(): VendorCartBucket[] {
    return this.cartState?.buckets ?? [];
  }

  get isEmpty(): boolean {
    return !this.isLoading
        && !this.orderSuccess
        && (this.cartState?.buckets?.length ?? 0) === 0;
  }

  get totalItemCount(): number {
    return this.buckets.reduce(
      (n, b) => n + b.items.reduce((m, i) => m + i.quantity, 0), 0
    );
  }

  formatReadyTime(iso: string | null): string {
    if (!iso) return '—';
    try {
      return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } catch { return iso; }
  }

  constructor() {
    afterNextRender(() => {
      const session = this.authSvc.getSession();
      if (!session?.userId) {
        this.router.navigate(['/login']);
        return;
      }
      this.userId = session.userId;

      this.sub = this.cartSvc.cart$.subscribe(state => {
        this.cartState = state;
        this.isLoading = false;
        this.cdr.detectChanges();
      });

      this.cartSvc.viewAllCarts(this.userId).subscribe({
        next:  () => { this.isLoading = false; this.cdr.detectChanges(); },
        error: () => { this.isLoading = false; this.hasError = true; this.cdr.detectChanges(); },
      });

      this.loadWalletBalance();
    });
  }

  ngOnInit(): void { /* session-bound work moved to afterNextRender */ }
  ngOnDestroy(): void { this.sub?.unsubscribe(); }

  private loadWalletBalance(): void {
    this.cartSvc.getWalletBalance(this.userId).subscribe({
      next: (res: WalletResponse) => {
        this.walletBalance = res.walletBalance;
        this.cdr.detectChanges();
      },
      error: () => console.error('Failed to load wallet balance'),
    });
  }

  /* ── Cart actions ───────────────────────────────────────── */
  add(item: CartItemDTO): void {
    this.cartSvc.addItem({
      userId: this.userId,
      menuItemId: item.menuItem.itemId,
      quantity: 1,
    });
  }

  reduce(item: CartItemDTO): void {
    this.cartSvc.reduceItem(this.userId, item.menuItem.itemId, item.orderItemId);
  }

  /* ── Place every cart bucket at once ────────────────────── */
  placeOrder(): void {
    if (this.isProcessing) return;
    const grandTotal = this.cartState?.totalAmount ?? 0;

    if (this.walletBalance < grandTotal) {
      this.orderError = 'Insufficient wallet balance. Please top up and try again.';
      this.cdr.detectChanges();
      return;
    }

    this.isProcessing  = true;
    this.orderError    = '';
    this.confirmedTotal = grandTotal;
    this.cdr.detectChanges();

    setTimeout(() => {
      this.cartSvc.placeAll(this.userId).subscribe({
        next: (orders: CartResponseDTO[]) => {
          this.isProcessing = false;
          this.orderSuccess = true;
          this.confirmedOrders = (orders ?? []).map(o => ({
            token: o.tokenNumber ?? '',
            vendor: o.vendor?.vendorName || o.vendor?.name || 'Vendor',
            amount: o.totalAmount ?? 0,
          }));
          this.cartSvc.clearCart();
          this.loadWalletBalance();
          if (this.confirmedOrders.length === 1) {
            this.toast.success(`Order placed — token ${this.confirmedOrders[0].token}`);
          } else {
            this.toast.success(`${this.confirmedOrders.length} orders placed across vendors`);
          }
          this.cdr.detectChanges();
        },
        error: (err) => {
          this.isProcessing = false;

          // The backend speaks three error shapes here:
          //   (a) HTTP 409 + { error: "...", code: "OUT_OF_STOCK" }   → race lost
          //   (b) HTTP 402 + { error: "Insufficient wallet ..." }    → too poor
          //   (c) anything else                                        → generic
          // Any of (a) rolls back the wallet debit on the server, so we don't
          // need to refund client-side — we just refresh the wallet display.
          const status = err?.status as number | undefined;
          const body   = err?.error;
          const errMsg = (typeof body === 'string' ? body : body?.error || body?.message || '') + '';
          const code   = body?.code;

          const isOutOfStock =
            status === 409 ||
            code === 'OUT_OF_STOCK' ||
            errMsg.toLowerCase().includes('out of stock');

          if (isOutOfStock) {
            // Surface the server's specific item name if it was in the body.
            this.orderError = errMsg && errMsg.toLowerCase().includes('out of stock')
              ? errMsg
              : 'Sorry, this item just went out of stock!';
            this.toast.error(this.orderError);
            // Re-pull the live cart so the affected item's quantity refreshes
            // and the customer can decide what to do next.
            this.cartSvc.viewAllCarts(this.userId).subscribe();
          } else if (errMsg.toLowerCase().includes('insufficient')) {
            this.orderError = 'Insufficient wallet balance. Please top up and try again.';
            this.toast.error(this.orderError);
          } else {
            this.orderError = 'Payment failed. Please try again.';
            this.toast.error(this.orderError);
          }

          // The wallet was either never debited (race lost) or rolled back by
          // @Transactional — refresh either way so the displayed balance is
          // authoritative.
          this.loadWalletBalance();
          this.cdr.detectChanges();
        },
      });
    }, 1500);
  }

  goBack(): void { history.back(); }
}
